version: "2"

services:

  caddy:
    image: stevepacker/caddy-php7
    container_name: ambassador
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./IT-Ambassador/Caddyfile:/etc/Caddyfile"
      - "./IT-Ambassador:/srv"
      - "$HOME/.caddy:/root/.caddy"
